import { readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { root } from './toolchain.mjs';

const schema = JSON.parse(readFileSync(resolve(root, 'abi/records.json'), 'utf8'));
// Compact output deliberately shares the diagnostic summary, with an empty object span.
const diagnostic_fields = schema.records.find(record => record.kind === 19);
const compact_fields = schema.records.find(record => record.kind === 31);
if (diagnostic_fields.size !== compact_fields.size ||
    JSON.stringify(diagnostic_fields.fields) !== JSON.stringify(compact_fields.fields)) {
  throw Error('Gameplay output summary must retain the diagnostic layout');
}
const fieldWidths = { u32: 4, u64: 8, f64: 8 };
const cTypes = { u32: 'uint32_t', u64: 'uint64_t', f64: 'double' };
let odinSource = `// Generated by scripts/generate-abi.mjs; edit abi/records.json.
package engine_runtime

ABI_RECORD_KIND_OFFSET :: 0
ABI_RECORD_VERSION_OFFSET :: 2
ABI_RECORD_BYTE_SIZE_OFFSET :: 4
ABI_ARRAY_OFFSET_OFFSET :: 0
ABI_ARRAY_COUNT_OFFSET :: 4
ABI_ARRAY_STRIDE_OFFSET :: 8
`;

for (const record of schema.records) {
  if (record.size % 8 || record.size < 8) throw Error('Invalid record size');
  const occupiedBytes = new Set([...Array(8).keys()]);
  for (const [fieldName, [fieldOffset, fieldType]] of Object.entries(record.fields)) {
    const fieldWidth = fieldWidths[fieldType];
    if (!fieldWidth || fieldOffset % fieldWidth || fieldOffset + fieldWidth > record.size) {
      throw Error('Invalid field ' + fieldName);
    }
    for (let byteOffset = fieldOffset; byteOffset < fieldOffset + fieldWidth; byteOffset++) {
      if (occupiedBytes.has(byteOffset)) throw Error('Overlapping fields');
      occupiedBytes.add(byteOffset);
    }
  }
  const prefix = `ABI_${record.name.toUpperCase()}`;
  odinSource += `${prefix}_KIND :: ${record.kind}\n${prefix}_SIZE :: ${record.size}\n`;
  for (const [fieldName, [fieldOffset]] of Object.entries(record.fields)) {
    odinSource += `${prefix}_${fieldName.toUpperCase()}_OFFSET :: ${fieldOffset}\n`;
  }
}

const javascriptSource = `// Generated by scripts/generate-abi.mjs; edit abi/records.json.
export const schema = ${JSON.stringify(schema, null, 2)};
export const field_widths = ${JSON.stringify(fieldWidths)};
const record_by_kind = new Map(schema.records.map(record => [record.kind, record]));
const RECORD_HEADER = schema.transport.record_header;
const fields_by_kind = new Map(schema.records.map(record => [record.kind, Object.entries(record.fields)]));

export function validateSpan(view, offset, count, stride, alignment = 1) {
  if (!Number.isSafeInteger(offset) || !Number.isSafeInteger(count) ||
      !Number.isSafeInteger(stride) || !Number.isSafeInteger(alignment) ||
      offset < 0 || count < 0 || stride <= 0 || alignment <= 0 || offset % alignment !== 0 ||
      offset > view.byteLength || count > Math.floor((view.byteLength - offset) / stride)) {
    throw new RangeError('Invalid ABI span');
  }
}

export function checkedSpan(view, offset, count, stride, alignment = 1) {
  validateSpan(view, offset, count, stride, alignment);
  return new Uint8Array(view.buffer, view.byteOffset + offset, count * stride);
}

export function readRecord(view, offset, kind) {
  return readRecordInto(view, offset, kind, {});
}

export function readRecordInto(view, offset, kind, result) {
  validateSpan(view, offset, RECORD_HEADER.size, 1, RECORD_HEADER.alignment);
  const record = record_by_kind.get(kind);
  if (!record || view.getUint16(offset + RECORD_HEADER.kind, true) !== kind || view.getUint16(offset + RECORD_HEADER.version, true) !== 1) {
    throw new Error('Unsupported record');
  }
  const size = view.getUint32(offset + RECORD_HEADER.byte_size, true);
  if (size < record.size || size % 8 !== 0) {
    throw new RangeError('Truncated record');
  }
  validateSpan(view, offset, size, 1, 8);
  const fields = fields_by_kind.get(kind);
  for (let field_index = 0; field_index < fields.length; field_index++) {
    const field_name = fields[field_index][0];
    const field_offset = fields[field_index][1][0];
    const field_type = fields[field_index][1][1];
    const address = offset + field_offset;
    switch (field_type) {
      case 'u32': result[field_name] = view.getUint32(address, true); break;
      case 'u64': result[field_name] = view.getBigUint64(address, true); break;
      case 'f64': result[field_name] = view.getFloat64(address, true); break;
    }
  }
  return result;
}

export function writeRecord(view, offset, kind, values = {}) {
  const record = record_by_kind.get(kind);
  if (!record) {
    throw new Error('Unsupported record');
  }
  const bytes = checkedSpan(view, offset, record.size, 1, 8);
  for (const field_name in values) {
    if (!Object.hasOwn(values, field_name)) continue;
    const value = values[field_name];
    const field = record.fields[field_name];
    if (!Object.hasOwn(record.fields, field_name)) {
      throw new Error('Unknown ABI field: ' + field_name);
    }
    const field_type = field[1];
    if ((field_type === 'u32' && (!Number.isInteger(value) || value < 0 || value > 0xffffffff)) ||
        (field_type === 'u64' && (typeof value !== 'bigint' || value < 0n || value > 0xffffffffffffffffn)) ||
        (field_type === 'f64' && !Number.isFinite(value))) {
      throw new RangeError('Invalid ABI value: ' + field_name);
    }
  }
  bytes.fill(0);
  view.setUint16(offset + RECORD_HEADER.kind, kind, true);
  view.setUint16(offset + RECORD_HEADER.version, 1, true);
  view.setUint32(offset + RECORD_HEADER.byte_size, record.size, true);
  for (const field_name in values) {
    if (!Object.hasOwn(values, field_name)) continue;
    const value = values[field_name];
    const field_offset = record.fields[field_name][0];
    const field_type = record.fields[field_name][1];
    const address = offset + field_offset;
    switch (field_type) {
      case 'u32': view.setUint32(address, value, true); break;
      case 'u64': view.setBigUint64(address, value, true); break;
      case 'f64': view.setFloat64(address, value, true); break;
    }
  }
}
`;
const typescriptSource = `// Generated by scripts/generate-abi.mjs; edit abi/records.json.
// Browser and TypeScript consumers execute the same checked implementation.
export { schema, field_widths, validateSpan, checkedSpan, readRecord, readRecordInto, writeRecord } from './records.mjs';
`;

let cSource = `/* Generated by scripts/generate-abi.mjs; edit abi/records.json. */
#pragma once
#include <stdint.h>
#include <stddef.h>
`;
for (const [field_name, field_offset] of Object.entries(schema.transport.mailbox)) {
  cSource += `#define OE_MAILBOX_${field_name.toUpperCase()} ${field_offset}\n`;
}
for (const record of schema.records) {
  cSource += 'typedef struct { uint16_t type, version; uint32_t byte_size;\n';
  for (const [fieldName, [, fieldType]] of Object.entries(record.fields)) {
    cSource += `  ${cTypes[fieldType]} ${fieldName};\n`;
  }
  cSource += `} oe_${record.name}_v1;\n`;
  cSource += `_Static_assert(sizeof(oe_${record.name}_v1)==${record.size}, "record size");\n`;
  for (const [fieldName, [fieldOffset]] of Object.entries(record.fields)) {
    cSource += `_Static_assert(offsetof(oe_${record.name}_v1, ${fieldName})==${fieldOffset}, "field offset");\n`;
  }
}
cSource += `typedef uint64_t oe_handle;
typedef struct { uint64_t address; uint32_t count, reserved; uint64_t token; } oe_byte_span;
uintptr_t oe_abi_control(void);
uint32_t oe_engine_create(const oe_engine_create_v1*, oe_handle*, oe_error_v1*);
uint32_t oe_engine_capabilities(oe_handle, oe_byte_span*);
uint32_t oe_preparation_capabilities(oe_handle, oe_byte_span*);
uint32_t oe_output_capabilities(oe_handle, oe_byte_span*);
uint32_t oe_simulation_capabilities(oe_handle, oe_byte_span*);
uint32_t oe_session_acknowledge(oe_handle, oe_handle, uint64_t token);
uint32_t oe_session_presentation(oe_handle, oe_handle, double time_ms, uintptr_t output);
uint32_t oe_playfield_transform(oe_handle, uintptr_t viewport, uintptr_t output);
uint32_t oe_session_bind_sample(oe_handle, oe_handle, uintptr_t binding);
uint32_t oe_session_replay_load(oe_handle, oe_handle, uint64_t token, uint32_t byte_count);
uint32_t oe_session_replay_export(oe_handle, oe_handle, uintptr_t output);
uint32_t oe_session_replay_seek(oe_handle, oe_handle, double time_ms, uintptr_t output);
uint32_t oe_buffer_reserve(oe_handle, uint32_t kind, uint64_t bytes, oe_byte_span*);
uint32_t oe_map_prepare(oe_handle, const oe_map_prepare_v1*, oe_handle*, oe_error_v1*);
uint32_t oe_map_describe(oe_handle, oe_handle, oe_byte_span*);
uint32_t oe_map_render_resources(oe_handle, oe_handle, uintptr_t output);
uint32_t oe_session_render_resources(oe_handle, oe_handle, uintptr_t output);
uint32_t oe_session_render_reserve(oe_handle, oe_handle, uintptr_t request, uintptr_t output);
uint32_t oe_session_draw(oe_handle, oe_handle, double time_ms, uintptr_t viewport, uintptr_t output);
uint32_t oe_transport_capabilities(oe_handle, uintptr_t output);
uint32_t oe_session_voice_reserve(oe_handle, oe_handle, uintptr_t request, uintptr_t output);
uint32_t oe_session_voice_output(oe_handle, oe_handle, uintptr_t output);
uint32_t oe_map_retain(oe_handle, oe_handle);
uint32_t oe_map_release(oe_handle, oe_handle);
uint32_t oe_session_create(oe_handle, oe_handle, const oe_session_create_v1*, oe_handle*, oe_error_v1*);
uint32_t oe_session_reset(oe_handle, oe_handle, double lead_in_ms);
uint32_t oe_session_release(oe_handle, oe_handle);
uint32_t oe_engine_release(oe_handle);
uint32_t oe_session_inputs(oe_handle, oe_handle, uintptr_t records, uintptr_t error);
uint32_t oe_session_inputs_from_reserved(oe_handle, oe_handle, uint64_t token, uint32_t count, uintptr_t error);
uint32_t oe_session_advance_output(oe_handle, oe_handle, double time_ms, uintptr_t output);
uint32_t oe_session_advance(oe_handle, oe_handle, double time_ms, uintptr_t output);
uint32_t oe_session_snapshot(oe_handle, oe_handle, double time_ms, uintptr_t output);
uint32_t oe_session_pause(oe_handle, oe_handle, double time_ms, uintptr_t output);
uint32_t oe_session_resume(oe_handle, oe_handle, uintptr_t anchor);
uint32_t oe_session_result(oe_handle, oe_handle, uintptr_t output);
`;

const declarationSource = `// Generated by scripts/generate-abi.mjs; edit abi/records.json.
export interface ABI_Record {
  name: string;
  kind: number;
  size: number;
  fields: Record<string, [number, 'u32' | 'u64' | 'f64']>;
}
export const schema: {
  abi_major: number;
  abi_minor: number;
  version: number;
  records: ABI_Record[];
  transport: {
    record_header: { kind: number; version: number; byte_size: number; size: number; alignment: number };
    mailbox: { creation: number; creation_size: number; result: number; error: number };
    byte_span: { size: number; address: number; count: number; reserved: number; token: number };
  };
};
export const field_widths: Record<'u32' | 'u64' | 'f64', number>;
export function checkedSpan(view: DataView, offset: number, count: number, stride: number, alignment?: number): Uint8Array;
export function validateSpan(view: DataView, offset: number, count: number, stride: number, alignment?: number): void;
export function readRecordInto(view: DataView, offset: number, kind: number, result: Record<string, number | bigint>): Record<string, number | bigint>;
export function readRecord(view: DataView, offset: number, kind: number): Record<string, number | bigint>;
export function writeRecord(view: DataView, offset: number, kind: number, values?: Record<string, number | bigint>): void;
`;

const generatedFiles = [
  ['runtime/abi_records.odin', odinSource],
  ['prepared/abi_records.odin', odinSource.replace('package engine_runtime', 'package prepared')],
  ['abi/records.ts', typescriptSource],
  ['abi/records.mjs', javascriptSource],
  ['abi/records.d.mts', declarationSource],
  ['abi/engine.h', cSource],
];
for (const [relativePath, contents] of generatedFiles) {
  const filePath = resolve(root, relativePath);
  if (process.argv.includes('--check')) {
    if (readFileSync(filePath, 'utf8') !== contents) {
      throw Error('Stale generated ABI: ' + relativePath);
    }
  } else {
    writeFileSync(filePath, contents);
  }
}
