import { readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { root } from './toolchain.mjs';

const schema = JSON.parse(readFileSync(resolve(root, 'abi/records.json'), 'utf8'));
const fieldWidths = { u32: 4, u64: 8, f64: 8 };
const cTypes = { u32: 'uint32_t', u64: 'uint64_t', f64: 'double' };
let odinSource = `// Generated by scripts/generate-abi.mjs; edit abi/records.json.
package engine_runtime

ABI_RECORD_KIND_OFFSET :: 0
ABI_RECORD_VERSION_OFFSET :: 2
ABI_RECORD_BYTE_SIZE_OFFSET :: 4
ABI_ARRAY_OFFSET_OFFSET :: 0
ABI_ARRAY_COUNT_OFFSET :: 4
ABI_ARRAY_STRIDE_OFFSET :: 8
`;

for (const record of schema.records) {
  if (record.size % 8 || record.size < 8) throw Error('Invalid record size');
  const occupiedBytes = new Set([...Array(8).keys()]);
  for (const [fieldName, [fieldOffset, fieldType]] of Object.entries(record.fields)) {
    const fieldWidth = fieldWidths[fieldType];
    if (!fieldWidth || fieldOffset % fieldWidth || fieldOffset + fieldWidth > record.size) {
      throw Error('Invalid field ' + fieldName);
    }
    for (let byteOffset = fieldOffset; byteOffset < fieldOffset + fieldWidth; byteOffset++) {
      if (occupiedBytes.has(byteOffset)) throw Error('Overlapping fields');
      occupiedBytes.add(byteOffset);
    }
  }
  const prefix = `ABI_${record.name.toUpperCase()}`;
  odinSource += `${prefix}_KIND :: ${record.kind}\n${prefix}_SIZE :: ${record.size}\n`;
  for (const [fieldName, [fieldOffset]] of Object.entries(record.fields)) {
    odinSource += `${prefix}_${fieldName.toUpperCase()}_OFFSET :: ${fieldOffset}\n`;
  }
}

const typescriptSource = `// Generated by scripts/generate-abi.mjs; edit abi/records.json.
export const schema = ${JSON.stringify(schema, null, 2)} as const;

export function readRecord(view: DataView, offset: number, kind: number): Record<string, number | bigint> {
  if (!Number.isSafeInteger(offset) || offset < 0 || offset % 8 || offset + 8 > view.byteLength) {
    throw Error('Invalid record span');
  }
  const record = schema.records.find(candidate => candidate.kind === kind);
  if (!record || view.getUint16(offset, true) !== kind || view.getUint16(offset + 2, true) !== 1) {
    throw Error('Unsupported record');
  }
  const size = view.getUint32(offset + 4, true);
  if (size < record.size || size % 8 || size > view.byteLength - offset) {
    throw Error('Truncated record');
  }
  const result: Record<string, number | bigint> = {};
  for (const [fieldName, [fieldOffset, fieldType]] of Object.entries(record.fields)) {
    const address = offset + fieldOffset;
    switch (fieldType) {
      case 'u32': result[fieldName] = view.getUint32(address, true); break;
      case 'u64': result[fieldName] = view.getBigUint64(address, true); break;
      case 'f64': result[fieldName] = view.getFloat64(address, true); break;
    }
  }
  return result;
}
`;

let cSource = `/* Generated by scripts/generate-abi.mjs; edit abi/records.json. */
#pragma once
#include <stdint.h>
#include <stddef.h>
`;
for (const record of schema.records) {
  cSource += 'typedef struct { uint16_t type, version; uint32_t byte_size;\n';
  for (const [fieldName, [, fieldType]] of Object.entries(record.fields)) {
    cSource += `  ${cTypes[fieldType]} ${fieldName};\n`;
  }
  cSource += `} oe_${record.name}_v1;\n`;
  cSource += `_Static_assert(sizeof(oe_${record.name}_v1)==${record.size}, "record size");\n`;
  for (const [fieldName, [fieldOffset]] of Object.entries(record.fields)) {
    cSource += `_Static_assert(offsetof(oe_${record.name}_v1, ${fieldName})==${fieldOffset}, "field offset");\n`;
  }
}
cSource += `typedef uint64_t oe_handle;
typedef struct { uint64_t address; uint32_t count, reserved; uint64_t token; } oe_byte_span;
uintptr_t oe_abi_control(void);
uint32_t oe_engine_create(const oe_engine_create_v1*, oe_handle*, oe_error_v1*);
uint32_t oe_engine_capabilities(oe_handle, oe_byte_span*);
uint32_t oe_preparation_capabilities(oe_handle, oe_byte_span*);
uint32_t oe_simulation_capabilities(oe_handle, oe_byte_span*);
uint32_t oe_session_acknowledge(oe_handle, oe_handle, uint64_t token);
uint32_t oe_session_bind_sample(oe_handle, oe_handle, uintptr_t binding);
uint32_t oe_session_replay_load(oe_handle, oe_handle, uint64_t token, uint32_t byte_count);
uint32_t oe_session_replay_export(oe_handle, oe_handle, uintptr_t output);
uint32_t oe_session_replay_seek(oe_handle, oe_handle, double time_ms, uintptr_t output);
uint32_t oe_buffer_reserve(oe_handle, uint32_t kind, uint64_t bytes, oe_byte_span*);
uint32_t oe_map_prepare(oe_handle, const oe_map_prepare_v1*, oe_handle*, oe_error_v1*);
uint32_t oe_map_describe(oe_handle, oe_handle, oe_byte_span*);
uint32_t oe_map_retain(oe_handle, oe_handle);
uint32_t oe_map_release(oe_handle, oe_handle);
uint32_t oe_session_create(oe_handle, oe_handle, const oe_session_create_v1*, oe_handle*, oe_error_v1*);
uint32_t oe_session_reset(oe_handle, oe_handle, double lead_in_ms);
uint32_t oe_session_release(oe_handle, oe_handle);
uint32_t oe_engine_release(oe_handle);
uint32_t oe_session_inputs(oe_handle, oe_handle, uintptr_t records, uintptr_t error);
uint32_t oe_session_inputs_from_reserved(oe_handle, oe_handle, uint64_t token, uint32_t count, uintptr_t error);
uint32_t oe_session_advance(oe_handle, oe_handle, double time_ms, uintptr_t output);
uint32_t oe_session_snapshot(oe_handle, oe_handle, double time_ms, uintptr_t output);
uint32_t oe_session_pause(oe_handle, oe_handle, double time_ms, uintptr_t output);
uint32_t oe_session_resume(oe_handle, oe_handle, uintptr_t anchor);
uint32_t oe_session_result(oe_handle, oe_handle, uintptr_t output);
`;

const generatedFiles = [
  ['runtime/abi_records.odin', odinSource],
  ['prepared/abi_records.odin', odinSource.replace('package engine_runtime', 'package prepared')],
  ['abi/records.ts', typescriptSource],
  ['abi/engine.h', cSource],
];
for (const [relativePath, contents] of generatedFiles) {
  const filePath = resolve(root, relativePath);
  if (process.argv.includes('--check')) {
    if (readFileSync(filePath, 'utf8') !== contents) {
      throw Error('Stale generated ABI: ' + relativePath);
    }
  } else {
    writeFileSync(filePath, contents);
  }
}
