// Generated by scripts/generate-abi.mjs; edit abi/records.json.
export interface ABI_Record {
  name: string;
  kind: number;
  size: number;
  fields: Record<string, [number, 'u32' | 'u64' | 'f64']>;
}
export const schema: {
  abi_major: number;
  abi_minor: number;
  version: number;
  records: ABI_Record[];
  transport: {
    mailbox: { creation: number; creation_size: number; result: number; error: number };
    byte_span: { size: number; address: number; count: number; reserved: number; token: number };
  };
};
export const field_widths: Record<'u32' | 'u64' | 'f64', number>;
export function checkedSpan(view: DataView, offset: number, count: number, stride: number, alignment?: number): Uint8Array;
export function readRecord(view: DataView, offset: number, kind: number): Record<string, number | bigint>;
export function writeRecord(view: DataView, offset: number, kind: number, values?: Record<string, number | bigint>): void;
