// Generated by scripts/generate-abi.mjs; edit abi/records.json.
// Browser and TypeScript consumers execute the same checked implementation.
export { schema, field_widths, validateSpan, checkedSpan, readRecord, readRecordInto, writeRecord } from './records.mjs';
