// Generated by scripts/generate-abi.mjs; edit abi/records.json.
export const schema = {
  "abi_major": 2,
  "abi_minor": 0,
  "version": 1,
  "records": [
    {
      "name": "engine_create",
      "kind": 1,
      "size": 16,
      "fields": {
        "flags": [
          8,
          "u32"
        ],
        "reserved": [
          12,
          "u32"
        ]
      }
    },
    {
      "name": "map_prepare",
      "kind": 2,
      "size": 32,
      "fields": {
        "token": [
          8,
          "u64"
        ],
        "offset": [
          16,
          "u32"
        ],
        "count": [
          20,
          "u32"
        ],
        "flags": [
          24,
          "u32"
        ],
        "reserved": [
          28,
          "u32"
        ]
      }
    },
    {
      "name": "session_create",
      "kind": 3,
      "size": 32,
      "fields": {
        "flags": [
          8,
          "u32"
        ],
        "reserved": [
          12,
          "u32"
        ],
        "arena_bytes": [
          16,
          "u64"
        ],
        "lead_in_ms": [
          24,
          "f64"
        ]
      }
    },
    {
      "name": "capabilities",
      "kind": 4,
      "size": 64,
      "fields": {
        "abi_major": [
          8,
          "u32"
        ],
        "abi_minor": [
          12,
          "u32"
        ],
        "foundation": [
          16,
          "u32"
        ],
        "gameplay": [
          20,
          "u32"
        ],
        "legacy_max": [
          24,
          "u32"
        ],
        "lazer_version": [
          28,
          "u32"
        ],
        "raw_bytes": [
          32,
          "u64"
        ],
        "arena_bytes": [
          40,
          "u64"
        ],
        "build_id": [
          48,
          "u64"
        ],
        "behavior_id": [
          56,
          "u32"
        ],
        "numeric_mode": [
          60,
          "u32"
        ]
      }
    },
    {
      "name": "map_descriptor",
      "kind": 5,
      "size": 32,
      "fields": {
        "format_version": [
          8,
          "u32"
        ],
        "foundation": [
          12,
          "u32"
        ],
        "objects": [
          16,
          "u32"
        ],
        "raw_timing": [
          20,
          "u32"
        ],
        "live_arena_bytes": [
          24,
          "u64"
        ]
      }
    },
    {
      "name": "error",
      "kind": 7,
      "size": 64,
      "fields": {
        "status": [
          8,
          "u32"
        ],
        "code": [
          12,
          "u32"
        ],
        "line": [
          16,
          "u32"
        ],
        "column": [
          20,
          "u32"
        ],
        "requested": [
          24,
          "u64"
        ],
        "limit": [
          32,
          "u64"
        ],
        "severity": [
          40,
          "u32"
        ],
        "related_id": [
          44,
          "u32"
        ],
        "message_offset": [
          48,
          "u32"
        ],
        "message_count": [
          52,
          "u32"
        ],
        "message_stride": [
          56,
          "u32"
        ],
        "reserved": [
          60,
          "u32"
        ]
      }
    },
    {
      "name": "prepared_descriptor",
      "kind": 8,
      "size": 248,
      "fields": {
        "behavior_id": [
          8,
          "u32"
        ],
        "numeric_mode": [
          12,
          "u32"
        ],
        "objects_offset": [
          16,
          "u32"
        ],
        "objects_count": [
          20,
          "u32"
        ],
        "objects_stride": [
          24,
          "u32"
        ],
        "schedule_offset": [
          28,
          "u32"
        ],
        "schedule_count": [
          32,
          "u32"
        ],
        "schedule_stride": [
          36,
          "u32"
        ],
        "raw_digest_0": [
          40,
          "u64"
        ],
        "raw_digest_1": [
          48,
          "u64"
        ],
        "raw_digest_2": [
          56,
          "u64"
        ],
        "raw_digest_3": [
          64,
          "u64"
        ],
        "prepared_digest_0": [
          72,
          "u64"
        ],
        "prepared_digest_1": [
          80,
          "u64"
        ],
        "prepared_digest_2": [
          88,
          "u64"
        ],
        "prepared_digest_3": [
          96,
          "u64"
        ],
        "total_bytes": [
          104,
          "u64"
        ],
        "hp": [
          112,
          "f64"
        ],
        "cs": [
          120,
          "f64"
        ],
        "od": [
          128,
          "f64"
        ],
        "ar": [
          136,
          "f64"
        ],
        "slider_multiplier": [
          144,
          "f64"
        ],
        "tick_rate": [
          152,
          "f64"
        ],
        "stack_leniency": [
          160,
          "f64"
        ],
        "breaks_offset": [
          168,
          "u32"
        ],
        "breaks_count": [
          172,
          "u32"
        ],
        "breaks_stride": [
          176,
          "u32"
        ],
        "timing_points_offset": [
          180,
          "u32"
        ],
        "timing_points_count": [
          184,
          "u32"
        ],
        "timing_points_stride": [
          188,
          "u32"
        ],
        "difficulty_points_offset": [
          192,
          "u32"
        ],
        "difficulty_points_count": [
          196,
          "u32"
        ],
        "difficulty_points_stride": [
          200,
          "u32"
        ],
        "sample_points_offset": [
          204,
          "u32"
        ],
        "sample_points_count": [
          208,
          "u32"
        ],
        "sample_points_stride": [
          212,
          "u32"
        ],
        "effect_points_offset": [
          216,
          "u32"
        ],
        "effect_points_count": [
          220,
          "u32"
        ],
        "effect_points_stride": [
          224,
          "u32"
        ],
        "playback_offset": [
          228,
          "u32"
        ],
        "playback_count": [
          232,
          "u32"
        ],
        "playback_stride": [
          236,
          "u32"
        ],
        "format_version": [
          240,
          "u32"
        ],
        "reserved_244": [
          244,
          "u32"
        ]
      }
    },
    {
      "name": "prepared_object",
      "kind": 9,
      "size": 272,
      "fields": {
        "id": [
          8,
          "u32"
        ],
        "kind": [
          12,
          "u32"
        ],
        "time_ms": [
          16,
          "f64"
        ],
        "end_time_ms": [
          24,
          "f64"
        ],
        "position_x": [
          32,
          "f64"
        ],
        "position_y": [
          40,
          "f64"
        ],
        "end_position_x": [
          48,
          "f64"
        ],
        "end_position_y": [
          56,
          "f64"
        ],
        "stack_offset_x": [
          64,
          "f64"
        ],
        "stack_offset_y": [
          72,
          "f64"
        ],
        "scale": [
          80,
          "f64"
        ],
        "radius": [
          88,
          "f64"
        ],
        "preempt_ms": [
          96,
          "f64"
        ],
        "fade_in_ms": [
          104,
          "f64"
        ],
        "stack_height": [
          112,
          "u32"
        ],
        "combo_index": [
          116,
          "u32"
        ],
        "combo_index_with_offsets": [
          120,
          "u32"
        ],
        "index_in_combo": [
          124,
          "u32"
        ],
        "new_combo": [
          128,
          "u32"
        ],
        "last_in_combo": [
          132,
          "u32"
        ],
        "combo_offset": [
          136,
          "u32"
        ],
        "spans": [
          140,
          "u32"
        ],
        "velocity": [
          144,
          "f64"
        ],
        "span_duration": [
          152,
          "f64"
        ],
        "tick_distance": [
          160,
          "f64"
        ],
        "path_distance": [
          168,
          "f64"
        ],
        "calculated_distance": [
          176,
          "f64"
        ],
        "generate_ticks": [
          184,
          "u32"
        ],
        "spins_required": [
          188,
          "u32"
        ],
        "maximum_bonus_spins": [
          192,
          "u32"
        ],
        "vertices_offset": [
          196,
          "u32"
        ],
        "vertices_count": [
          200,
          "u32"
        ],
        "vertices_stride": [
          204,
          "u32"
        ],
        "cumulative_offset": [
          208,
          "u32"
        ],
        "cumulative_count": [
          212,
          "u32"
        ],
        "cumulative_stride": [
          216,
          "u32"
        ],
        "samples_offset": [
          220,
          "u32"
        ],
        "samples_count": [
          224,
          "u32"
        ],
        "samples_stride": [
          228,
          "u32"
        ],
        "tail_samples_offset": [
          232,
          "u32"
        ],
        "tail_samples_count": [
          236,
          "u32"
        ],
        "tail_samples_stride": [
          240,
          "u32"
        ],
        "auxiliary_samples_offset": [
          244,
          "u32"
        ],
        "auxiliary_samples_count": [
          248,
          "u32"
        ],
        "auxiliary_samples_stride": [
          252,
          "u32"
        ],
        "components_offset": [
          256,
          "u32"
        ],
        "components_count": [
          260,
          "u32"
        ],
        "components_stride": [
          264,
          "u32"
        ],
        "reserved_268": [
          268,
          "u32"
        ]
      }
    },
    {
      "name": "prepared_component",
      "kind": 10,
      "size": 80,
      "fields": {
        "id": [
          8,
          "u32"
        ],
        "kind": [
          12,
          "u32"
        ],
        "time_ms": [
          16,
          "f64"
        ],
        "span_start_ms": [
          24,
          "f64"
        ],
        "progress": [
          32,
          "f64"
        ],
        "position_x": [
          40,
          "f64"
        ],
        "position_y": [
          48,
          "f64"
        ],
        "span_index": [
          56,
          "u32"
        ],
        "samples_offset": [
          60,
          "u32"
        ],
        "samples_count": [
          64,
          "u32"
        ],
        "samples_stride": [
          68,
          "u32"
        ],
        "event_time_ms": [
          72,
          "f64"
        ]
      }
    },
    {
      "name": "prepared_sample",
      "kind": 11,
      "size": 72,
      "fields": {
        "name_offset": [
          8,
          "u32"
        ],
        "name_count": [
          12,
          "u32"
        ],
        "name_stride": [
          16,
          "u32"
        ],
        "bank_offset": [
          20,
          "u32"
        ],
        "bank_count": [
          24,
          "u32"
        ],
        "bank_stride": [
          28,
          "u32"
        ],
        "suffix_offset": [
          32,
          "u32"
        ],
        "suffix_count": [
          36,
          "u32"
        ],
        "suffix_stride": [
          40,
          "u32"
        ],
        "volume": [
          44,
          "u32"
        ],
        "use_beatmap": [
          48,
          "u32"
        ],
        "layered": [
          52,
          "u32"
        ],
        "candidates_offset": [
          56,
          "u32"
        ],
        "candidates_count": [
          60,
          "u32"
        ],
        "candidates_stride": [
          64,
          "u32"
        ],
        "flags": [
          68,
          "u32"
        ]
      }
    },
    {
      "name": "sample_candidate",
      "kind": 12,
      "size": 24,
      "fields": {
        "name_offset": [
          8,
          "u32"
        ],
        "name_count": [
          12,
          "u32"
        ],
        "name_stride": [
          16,
          "u32"
        ],
        "reserved_20": [
          20,
          "u32"
        ]
      }
    },
    {
      "name": "prepared_schedule",
      "kind": 13,
      "size": 24,
      "fields": {
        "time_ms": [
          8,
          "f64"
        ],
        "object_index": [
          16,
          "u32"
        ],
        "component_index": [
          20,
          "u32"
        ]
      }
    },
    {
      "name": "preparation_capabilities",
      "kind": 14,
      "size": 24,
      "fields": {
        "preparation_version": [
          8,
          "u32"
        ],
        "behavior_id": [
          12,
          "u32"
        ],
        "numeric_mode": [
          16,
          "u32"
        ],
        "reserved": [
          20,
          "u32"
        ]
      }
    },
    {
      "name": "prepared_break",
      "kind": 15,
      "size": 24,
      "fields": {
        "start_ms": [
          8,
          "f64"
        ],
        "end_ms": [
          16,
          "f64"
        ]
      }
    },
    {
      "name": "prepared_control_point",
      "kind": 16,
      "size": 64,
      "fields": {
        "time_ms": [
          8,
          "f64"
        ],
        "beat_length": [
          16,
          "f64"
        ],
        "slider_velocity": [
          24,
          "f64"
        ],
        "source_id": [
          32,
          "u32"
        ],
        "meter": [
          36,
          "u32"
        ],
        "sample_set": [
          40,
          "u32"
        ],
        "sample_index": [
          44,
          "u32"
        ],
        "volume": [
          48,
          "u32"
        ],
        "generate_ticks": [
          52,
          "u32"
        ],
        "kiai": [
          56,
          "u32"
        ],
        "omit_first_bar": [
          60,
          "u32"
        ]
      }
    },
    {
      "name": "prepared_playback",
      "kind": 17,
      "size": 72,
      "fields": {
        "audio_lead_in": [
          8,
          "f64"
        ],
        "preview_time": [
          16,
          "f64"
        ],
        "sample_set": [
          24,
          "u32"
        ],
        "sample_volume": [
          28,
          "u32"
        ],
        "countdown": [
          32,
          "u32"
        ],
        "countdown_offset": [
          36,
          "u32"
        ],
        "samples_match_playback_rate": [
          40,
          "u32"
        ],
        "letterbox_in_breaks": [
          44,
          "u32"
        ],
        "epilepsy_warning": [
          48,
          "u32"
        ],
        "widescreen_storyboard": [
          52,
          "u32"
        ],
        "special_style": [
          56,
          "u32"
        ],
        "audio_filename_offset": [
          60,
          "u32"
        ],
        "audio_filename_count": [
          64,
          "u32"
        ],
        "audio_filename_stride": [
          68,
          "u32"
        ]
      }
    },
    {
      "name": "gameplay_create",
      "kind": 18,
      "size": 40,
      "fields": {
        "flags": [
          8,
          "u32"
        ],
        "reserved": [
          12,
          "u32"
        ],
        "arena_bytes": [
          16,
          "u64"
        ],
        "lead_in_ms": [
          24,
          "f64"
        ],
        "input_capacity": [
          32,
          "u32"
        ],
        "reserved_36": [
          36,
          "u32"
        ]
      }
    },
    {
      "name": "session_snapshot",
      "kind": 19,
      "size": 120,
      "fields": {
        "state": [
          8,
          "u32"
        ],
        "epoch": [
          12,
          "u32"
        ],
        "committed_ms": [
          16,
          "f64"
        ],
        "presentation_ms": [
          24,
          "f64"
        ],
        "score": [
          32,
          "u64"
        ],
        "accuracy": [
          40,
          "f64"
        ],
        "health": [
          48,
          "f64"
        ],
        "combo": [
          56,
          "u32"
        ],
        "highest_combo": [
          60,
          "u32"
        ],
        "objects_offset": [
          64,
          "u32"
        ],
        "objects_count": [
          68,
          "u32"
        ],
        "objects_stride": [
          72,
          "u32"
        ],
        "judgements_offset": [
          76,
          "u32"
        ],
        "judgements_count": [
          80,
          "u32"
        ],
        "judgements_stride": [
          84,
          "u32"
        ],
        "batch_token": [
          88,
          "u64"
        ],
        "total_bytes": [
          96,
          "u64"
        ],
        "audio_offset": [
          104,
          "u32"
        ],
        "audio_count": [
          108,
          "u32"
        ],
        "audio_stride": [
          112,
          "u32"
        ],
        "reserved": [
          116,
          "u32"
        ]
      }
    },
    {
      "name": "session_object",
      "kind": 20,
      "size": 64,
      "fields": {
        "object_id": [
          8,
          "u32"
        ],
        "result": [
          12,
          "u32"
        ],
        "head_result": [
          16,
          "u32"
        ],
        "tracking": [
          20,
          "u32"
        ],
        "result_time_ms": [
          24,
          "f64"
        ],
        "head_time_ms": [
          32,
          "f64"
        ],
        "rotation": [
          40,
          "f64"
        ],
        "position_x": [
          48,
          "f64"
        ],
        "position_y": [
          56,
          "f64"
        ]
      }
    },
    {
      "name": "judgement",
      "kind": 21,
      "size": 80,
      "fields": {
        "sequence": [
          8,
          "u64"
        ],
        "time_ms": [
          16,
          "f64"
        ],
        "object_id": [
          24,
          "u32"
        ],
        "component_id": [
          28,
          "u32"
        ],
        "result": [
          32,
          "u32"
        ],
        "cause": [
          36,
          "u32"
        ],
        "offset_ms": [
          40,
          "f64"
        ],
        "combo_before": [
          48,
          "u32"
        ],
        "combo_after": [
          52,
          "u32"
        ],
        "health_before": [
          56,
          "f64"
        ],
        "health_after": [
          64,
          "f64"
        ],
        "score_after": [
          72,
          "u64"
        ]
      }
    },
    {
      "name": "clock_anchor",
      "kind": 22,
      "size": 40,
      "fields": {
        "beatmap_ms": [
          8,
          "f64"
        ],
        "audio_seconds": [
          16,
          "f64"
        ],
        "rate": [
          24,
          "f64"
        ],
        "flags": [
          32,
          "u32"
        ],
        "reserved": [
          36,
          "u32"
        ]
      }
    },
    {
      "name": "input_snapshot",
      "kind": 23,
      "size": 64,
      "fields": {
        "sequence": [
          8,
          "u64"
        ],
        "raw_time_ms": [
          16,
          "f64"
        ],
        "effective_time_ms": [
          24,
          "f64"
        ],
        "x": [
          32,
          "f64"
        ],
        "y": [
          40,
          "f64"
        ],
        "action_bits": [
          48,
          "u32"
        ],
        "source_focus": [
          52,
          "u32"
        ],
        "flags": [
          56,
          "u32"
        ],
        "reserved": [
          60,
          "u32"
        ]
      }
    },
    {
      "name": "final_result",
      "kind": 24,
      "size": 232,
      "fields": {
        "state": [
          8,
          "u32"
        ],
        "rank": [
          12,
          "u32"
        ],
        "terminal_ms": [
          16,
          "f64"
        ],
        "score": [
          24,
          "u64"
        ],
        "accuracy": [
          32,
          "f64"
        ],
        "health": [
          40,
          "f64"
        ],
        "numerator": [
          48,
          "u64"
        ],
        "denominator": [
          56,
          "u64"
        ],
        "combo": [
          64,
          "u32"
        ],
        "highest_combo": [
          68,
          "u32"
        ],
        "raw_digest_0": [
          72,
          "u64"
        ],
        "raw_digest_1": [
          80,
          "u64"
        ],
        "raw_digest_2": [
          88,
          "u64"
        ],
        "raw_digest_3": [
          96,
          "u64"
        ],
        "prepared_digest_0": [
          104,
          "u64"
        ],
        "prepared_digest_1": [
          112,
          "u64"
        ],
        "prepared_digest_2": [
          120,
          "u64"
        ],
        "prepared_digest_3": [
          128,
          "u64"
        ],
        "judgement_digest_0": [
          136,
          "u64"
        ],
        "judgement_digest_1": [
          144,
          "u64"
        ],
        "judgement_digest_2": [
          152,
          "u64"
        ],
        "judgement_digest_3": [
          160,
          "u64"
        ],
        "counts_offset": [
          168,
          "u32"
        ],
        "counts_count": [
          172,
          "u32"
        ],
        "counts_stride": [
          176,
          "u32"
        ],
        "behavior_id": [
          180,
          "u32"
        ],
        "rules_version": [
          184,
          "u32"
        ],
        "abi_major": [
          188,
          "u32"
        ],
        "rate": [
          192,
          "f64"
        ],
        "offset_0": [
          200,
          "f64"
        ],
        "offset_1": [
          208,
          "f64"
        ],
        "offset_2": [
          216,
          "f64"
        ],
        "offset_3": [
          224,
          "f64"
        ]
      }
    },
    {
      "name": "simulation_capabilities",
      "kind": 25,
      "size": 24,
      "fields": {
        "simulation_version": [
          8,
          "u32"
        ],
        "rules_version": [
          12,
          "u32"
        ],
        "flags": [
          16,
          "u32"
        ],
        "max_inputs": [
          20,
          "u32"
        ]
      }
    },
    {
      "name": "result_count",
      "kind": 26,
      "size": 24,
      "fields": {
        "result": [
          8,
          "u32"
        ],
        "actual": [
          12,
          "u32"
        ],
        "maximum": [
          16,
          "u32"
        ],
        "reserved": [
          20,
          "u32"
        ]
      }
    },
    {
      "name": "audio_event",
      "kind": 27,
      "size": 64,
      "fields": {
        "sequence": [
          8,
          "u64"
        ],
        "epoch": [
          16,
          "u32"
        ],
        "flags": [
          20,
          "u32"
        ],
        "time_ms": [
          24,
          "f64"
        ],
        "asset_id": [
          32,
          "u64"
        ],
        "volume": [
          40,
          "f64"
        ],
        "object_id": [
          48,
          "u32"
        ],
        "component_id": [
          52,
          "u32"
        ],
        "sample_index": [
          56,
          "u32"
        ],
        "kind": [
          60,
          "u32"
        ]
      }
    },
    {
      "name": "sample_binding",
      "kind": 28,
      "size": 32,
      "fields": {
        "object_id": [
          8,
          "u32"
        ],
        "component_id": [
          12,
          "u32"
        ],
        "sample_index": [
          16,
          "u32"
        ],
        "candidate_index": [
          20,
          "u32"
        ],
        "asset_id": [
          24,
          "u64"
        ]
      }
    },
    {
      "name": "viewport",
      "kind": 29,
      "size": 48,
      "fields": {
        "css_left": [
          8,
          "f64"
        ],
        "css_top": [
          16,
          "f64"
        ],
        "css_width": [
          24,
          "f64"
        ],
        "css_height": [
          32,
          "f64"
        ],
        "device_pixel_ratio": [
          40,
          "f64"
        ]
      }
    },
    {
      "name": "playfield_transform",
      "kind": 30,
      "size": 80,
      "fields": {
        "scale": [
          8,
          "f64"
        ],
        "client_left": [
          16,
          "f64"
        ],
        "client_top": [
          24,
          "f64"
        ],
        "inverse_a": [
          32,
          "f64"
        ],
        "inverse_b": [
          40,
          "f64"
        ],
        "inverse_c": [
          48,
          "f64"
        ],
        "inverse_d": [
          56,
          "f64"
        ],
        "inverse_e": [
          64,
          "f64"
        ],
        "inverse_f": [
          72,
          "f64"
        ]
      }
    },
    {
      "name": "gameplay_output",
      "kind": 31,
      "size": 120,
      "fields": {
        "state": [
          8,
          "u32"
        ],
        "epoch": [
          12,
          "u32"
        ],
        "committed_ms": [
          16,
          "f64"
        ],
        "presentation_ms": [
          24,
          "f64"
        ],
        "score": [
          32,
          "u64"
        ],
        "accuracy": [
          40,
          "f64"
        ],
        "health": [
          48,
          "f64"
        ],
        "combo": [
          56,
          "u32"
        ],
        "highest_combo": [
          60,
          "u32"
        ],
        "objects_offset": [
          64,
          "u32"
        ],
        "objects_count": [
          68,
          "u32"
        ],
        "objects_stride": [
          72,
          "u32"
        ],
        "judgements_offset": [
          76,
          "u32"
        ],
        "judgements_count": [
          80,
          "u32"
        ],
        "judgements_stride": [
          84,
          "u32"
        ],
        "batch_token": [
          88,
          "u64"
        ],
        "total_bytes": [
          96,
          "u64"
        ],
        "audio_offset": [
          104,
          "u32"
        ],
        "audio_count": [
          108,
          "u32"
        ],
        "audio_stride": [
          112,
          "u32"
        ],
        "reserved": [
          116,
          "u32"
        ]
      }
    },
    {
      "name": "presentation_frame",
      "kind": 32,
      "size": 88,
      "fields": {
        "state": [
          8,
          "u32"
        ],
        "epoch": [
          12,
          "u32"
        ],
        "committed_ms": [
          16,
          "f64"
        ],
        "presentation_ms": [
          24,
          "f64"
        ],
        "objects_offset": [
          32,
          "u32"
        ],
        "objects_count": [
          36,
          "u32"
        ],
        "objects_stride": [
          40,
          "u32"
        ],
        "reserved": [
          44,
          "u32"
        ],
        "total_bytes": [
          48,
          "u64"
        ],
        "visited_count": [
          56,
          "u64"
        ],
        "revealed_count": [
          64,
          "u64"
        ],
        "cursor_x": [
          72,
          "f64"
        ],
        "cursor_y": [
          80,
          "f64"
        ]
      }
    },
    {
      "name": "presentation_object",
      "kind": 33,
      "size": 96,
      "fields": {
        "object_id": [
          8,
          "u32"
        ],
        "object_kind": [
          12,
          "u32"
        ],
        "result": [
          16,
          "u32"
        ],
        "head_result": [
          20,
          "u32"
        ],
        "tracking": [
          24,
          "u32"
        ],
        "reserved": [
          28,
          "u32"
        ],
        "result_time_ms": [
          32,
          "f64"
        ],
        "head_time_ms": [
          40,
          "f64"
        ],
        "position_x": [
          48,
          "f64"
        ],
        "position_y": [
          56,
          "f64"
        ],
        "rotation": [
          64,
          "f64"
        ],
        "start_time_ms": [
          72,
          "f64"
        ],
        "radius": [
          80,
          "f64"
        ],
        "preempt_ms": [
          88,
          "f64"
        ]
      }
    },
    {
      "name": "output_capabilities",
      "kind": 34,
      "size": 24,
      "fields": {
        "compact_version": [
          8,
          "u32"
        ],
        "projection_version": [
          12,
          "u32"
        ],
        "flags": [
          16,
          "u32"
        ],
        "reserved": [
          20,
          "u32"
        ]
      }
    },
    {
      "name": "render_resource",
      "kind": 35,
      "size": 160,
      "fields": {
        "resource_id": [
          8,
          "u64"
        ],
        "attachment_version": [
          16,
          "u32"
        ],
        "flags": [
          20,
          "u32"
        ],
        "total_bytes": [
          24,
          "u64"
        ],
        "prepared_digest_0": [
          32,
          "u64"
        ],
        "prepared_digest_1": [
          40,
          "u64"
        ],
        "prepared_digest_2": [
          48,
          "u64"
        ],
        "prepared_digest_3": [
          56,
          "u64"
        ],
        "vertices_offset": [
          64,
          "u32"
        ],
        "vertices_count": [
          68,
          "u32"
        ],
        "vertices_stride": [
          72,
          "u32"
        ],
        "vertices_reserved": [
          76,
          "u32"
        ],
        "indices_offset": [
          80,
          "u32"
        ],
        "indices_count": [
          84,
          "u32"
        ],
        "indices_stride": [
          88,
          "u32"
        ],
        "indices_reserved": [
          92,
          "u32"
        ],
        "atlas_offset": [
          96,
          "u32"
        ],
        "atlas_count": [
          100,
          "u32"
        ],
        "atlas_stride": [
          104,
          "u32"
        ],
        "atlas_reserved": [
          108,
          "u32"
        ],
        "vertex_shader_offset": [
          112,
          "u32"
        ],
        "vertex_shader_count": [
          116,
          "u32"
        ],
        "vertex_shader_stride": [
          120,
          "u32"
        ],
        "vertex_shader_reserved": [
          124,
          "u32"
        ],
        "fragment_shader_offset": [
          128,
          "u32"
        ],
        "fragment_shader_count": [
          132,
          "u32"
        ],
        "fragment_shader_stride": [
          136,
          "u32"
        ],
        "fragment_shader_reserved": [
          140,
          "u32"
        ],
        "atlas_width": [
          144,
          "u32"
        ],
        "atlas_height": [
          148,
          "u32"
        ],
        "reserved": [
          152,
          "u64"
        ]
      }
    },
    {
      "name": "render_reserve",
      "kind": 36,
      "size": 32,
      "fields": {
        "arena_bytes": [
          8,
          "u64"
        ],
        "instance_capacity": [
          16,
          "u32"
        ],
        "flags": [
          20,
          "u32"
        ],
        "reserved": [
          24,
          "u64"
        ]
      }
    },
    {
      "name": "render_capacity",
      "kind": 37,
      "size": 40,
      "fields": {
        "requested_instances": [
          8,
          "u32"
        ],
        "required_instances": [
          12,
          "u32"
        ],
        "required_bytes": [
          16,
          "u64"
        ],
        "resource_id": [
          24,
          "u64"
        ],
        "epoch": [
          32,
          "u32"
        ],
        "flags": [
          36,
          "u32"
        ]
      }
    },
    {
      "name": "draw_frame",
      "kind": 38,
      "size": 128,
      "fields": {
        "epoch": [
          8,
          "u32"
        ],
        "state": [
          12,
          "u32"
        ],
        "resource_id": [
          16,
          "u64"
        ],
        "presentation_ms": [
          24,
          "f64"
        ],
        "committed_ms": [
          32,
          "f64"
        ],
        "scale": [
          40,
          "f64"
        ],
        "client_left": [
          48,
          "f64"
        ],
        "client_top": [
          56,
          "f64"
        ],
        "score": [
          64,
          "u64"
        ],
        "accuracy": [
          72,
          "f64"
        ],
        "health": [
          80,
          "f64"
        ],
        "combo": [
          88,
          "u32"
        ],
        "highest_combo": [
          92,
          "u32"
        ],
        "instances_offset": [
          96,
          "u32"
        ],
        "instances_count": [
          100,
          "u32"
        ],
        "instances_stride": [
          104,
          "u32"
        ],
        "batches_offset": [
          108,
          "u32"
        ],
        "batches_count": [
          112,
          "u32"
        ],
        "batches_stride": [
          116,
          "u32"
        ],
        "total_bytes": [
          120,
          "u64"
        ]
      }
    },
    {
      "name": "draw_instance",
      "kind": 39,
      "size": 112,
      "fields": {
        "primitive": [
          8,
          "u32"
        ],
        "layer": [
          12,
          "u32"
        ],
        "object_id": [
          16,
          "u32"
        ],
        "component_id": [
          20,
          "u32"
        ],
        "ordinal": [
          24,
          "u32"
        ],
        "flags": [
          28,
          "u32"
        ],
        "x": [
          32,
          "f64"
        ],
        "y": [
          40,
          "f64"
        ],
        "scale_x": [
          48,
          "f64"
        ],
        "scale_y": [
          56,
          "f64"
        ],
        "rotation": [
          64,
          "f64"
        ],
        "alpha": [
          72,
          "f64"
        ],
        "progress": [
          80,
          "f64"
        ],
        "colour": [
          88,
          "u32"
        ],
        "glyph": [
          92,
          "u32"
        ],
        "geometry_first": [
          96,
          "u32"
        ],
        "geometry_count": [
          100,
          "u32"
        ],
        "reserved": [
          104,
          "u64"
        ]
      }
    },
    {
      "name": "draw_batch",
      "kind": 40,
      "size": 32,
      "fields": {
        "layer": [
          8,
          "u32"
        ],
        "primitive": [
          12,
          "u32"
        ],
        "first_instance": [
          16,
          "u32"
        ],
        "instance_count": [
          20,
          "u32"
        ],
        "reserved": [
          24,
          "u64"
        ]
      }
    },
    {
      "name": "transport_capabilities",
      "kind": 41,
      "size": 40,
      "fields": {
        "resource_version": [
          8,
          "u32"
        ],
        "circle_animation_version": [
          12,
          "u32"
        ],
        "draw_version": [
          16,
          "u32"
        ],
        "voice_version": [
          20,
          "u32"
        ],
        "voice_command_mask": [
          24,
          "u32"
        ],
        "flags": [
          28,
          "u32"
        ],
        "max_draw_instances": [
          32,
          "u32"
        ],
        "reserved": [
          36,
          "u32"
        ]
      }
    },
    {
      "name": "voice_reserve",
      "kind": 42,
      "size": 32,
      "fields": {
        "arena_bytes": [
          8,
          "u64"
        ],
        "command_capacity": [
          16,
          "u32"
        ],
        "flags": [
          20,
          "u32"
        ],
        "reserved": [
          24,
          "u64"
        ]
      }
    },
    {
      "name": "voice_capacity",
      "kind": 43,
      "size": 32,
      "fields": {
        "requested_commands": [
          8,
          "u32"
        ],
        "required_commands": [
          12,
          "u32"
        ],
        "required_bytes": [
          16,
          "u64"
        ],
        "epoch": [
          24,
          "u32"
        ],
        "flags": [
          28,
          "u32"
        ]
      }
    },
    {
      "name": "voice_frame",
      "kind": 44,
      "size": 64,
      "fields": {
        "epoch": [
          8,
          "u32"
        ],
        "flags": [
          12,
          "u32"
        ],
        "batch_token": [
          16,
          "u64"
        ],
        "committed_ms": [
          24,
          "f64"
        ],
        "commands_offset": [
          32,
          "u32"
        ],
        "commands_count": [
          36,
          "u32"
        ],
        "commands_stride": [
          40,
          "u32"
        ],
        "reserved": [
          44,
          "u32"
        ],
        "total_bytes": [
          48,
          "u64"
        ],
        "reserved_tail": [
          56,
          "u64"
        ]
      }
    },
    {
      "name": "voice_command",
      "kind": 45,
      "size": 112,
      "fields": {
        "sequence": [
          8,
          "u64"
        ],
        "epoch": [
          16,
          "u32"
        ],
        "command_kind": [
          20,
          "u32"
        ],
        "time_ms": [
          24,
          "f64"
        ],
        "voice_id": [
          32,
          "u64"
        ],
        "asset_id": [
          40,
          "u64"
        ],
        "volume": [
          48,
          "f64"
        ],
        "pan": [
          56,
          "f64"
        ],
        "rate": [
          64,
          "f64"
        ],
        "duration_ms": [
          72,
          "f64"
        ],
        "lateness_threshold_ms": [
          80,
          "f64"
        ],
        "parameter_mask": [
          88,
          "u32"
        ],
        "late_policy": [
          92,
          "u32"
        ],
        "object_id": [
          96,
          "u32"
        ],
        "component_id": [
          100,
          "u32"
        ],
        "flags": [
          104,
          "u32"
        ],
        "reserved": [
          108,
          "u32"
        ]
      }
    }
  ],
  "transport": {
    "mailbox": {
      "creation": 0,
      "creation_size": 256,
      "result": 256,
      "error": 320
    },
    "byte_span": {
      "size": 24,
      "address": 0,
      "count": 8,
      "reserved": 12,
      "token": 16
    },
    "record_header": {
      "kind": 0,
      "version": 2,
      "byte_size": 4,
      "size": 8,
      "alignment": 8
    }
  }
};
export const field_widths = {"u32":4,"u64":8,"f64":8};
const record_by_kind = new Map(schema.records.map(record => [record.kind, record]));
const RECORD_HEADER = schema.transport.record_header;
const fields_by_kind = new Map(schema.records.map(record => [record.kind, Object.entries(record.fields)]));

export function validateSpan(view, offset, count, stride, alignment = 1) {
  if (!Number.isSafeInteger(offset) || !Number.isSafeInteger(count) ||
      !Number.isSafeInteger(stride) || !Number.isSafeInteger(alignment) ||
      offset < 0 || count < 0 || stride <= 0 || alignment <= 0 || offset % alignment !== 0 ||
      offset > view.byteLength || count > Math.floor((view.byteLength - offset) / stride)) {
    throw new RangeError('Invalid ABI span');
  }
}

export function checkedSpan(view, offset, count, stride, alignment = 1) {
  validateSpan(view, offset, count, stride, alignment);
  return new Uint8Array(view.buffer, view.byteOffset + offset, count * stride);
}

export function readRecord(view, offset, kind) {
  return readRecordInto(view, offset, kind, {});
}

export function readRecordInto(view, offset, kind, result) {
  validateSpan(view, offset, RECORD_HEADER.size, 1, RECORD_HEADER.alignment);
  const record = record_by_kind.get(kind);
  if (!record || view.getUint16(offset + RECORD_HEADER.kind, true) !== kind || view.getUint16(offset + RECORD_HEADER.version, true) !== 1) {
    throw new Error('Unsupported record');
  }
  const size = view.getUint32(offset + RECORD_HEADER.byte_size, true);
  if (size < record.size || size % 8 !== 0) {
    throw new RangeError('Truncated record');
  }
  validateSpan(view, offset, size, 1, 8);
  const fields = fields_by_kind.get(kind);
  for (let field_index = 0; field_index < fields.length; field_index++) {
    const field_name = fields[field_index][0];
    const field_offset = fields[field_index][1][0];
    const field_type = fields[field_index][1][1];
    const address = offset + field_offset;
    switch (field_type) {
      case 'u32': result[field_name] = view.getUint32(address, true); break;
      case 'u64': result[field_name] = view.getBigUint64(address, true); break;
      case 'f64': result[field_name] = view.getFloat64(address, true); break;
    }
  }
  return result;
}

export function writeRecord(view, offset, kind, values = {}) {
  const record = record_by_kind.get(kind);
  if (!record) {
    throw new Error('Unsupported record');
  }
  const bytes = checkedSpan(view, offset, record.size, 1, 8);
  for (const field_name in values) {
    if (!Object.hasOwn(values, field_name)) continue;
    const value = values[field_name];
    const field = record.fields[field_name];
    if (!Object.hasOwn(record.fields, field_name)) {
      throw new Error('Unknown ABI field: ' + field_name);
    }
    const field_type = field[1];
    if ((field_type === 'u32' && (!Number.isInteger(value) || value < 0 || value > 0xffffffff)) ||
        (field_type === 'u64' && (typeof value !== 'bigint' || value < 0n || value > 0xffffffffffffffffn)) ||
        (field_type === 'f64' && !Number.isFinite(value))) {
      throw new RangeError('Invalid ABI value: ' + field_name);
    }
  }
  bytes.fill(0);
  view.setUint16(offset + RECORD_HEADER.kind, kind, true);
  view.setUint16(offset + RECORD_HEADER.version, 1, true);
  view.setUint32(offset + RECORD_HEADER.byte_size, record.size, true);
  for (const field_name in values) {
    if (!Object.hasOwn(values, field_name)) continue;
    const value = values[field_name];
    const field_offset = record.fields[field_name][0];
    const field_type = record.fields[field_name][1];
    const address = offset + field_offset;
    switch (field_type) {
      case 'u32': view.setUint32(address, value, true); break;
      case 'u64': view.setBigUint64(address, value, true); break;
      case 'f64': view.setFloat64(address, value, true); break;
    }
  }
}
